### ISSUE TITLE
setup couldn't find OGER

### ISSUE THREAD

**Issue by turbomam** [monarch-initiative/runner#6]
The suggested initial setup is

`python setup.py install`

On an Ubuntu 20 machine with no virtual environment activated yet, I did

`python3 setup.py install`

Which gave me 

> [Errno 13] Permission denied: '/usr/local/lib/python3.8/dist-packages/test-easy-install-55627.write-test'

So I did

`sudo python3 setup.py install`

Which seemed to install several packages, but it seemed to stop at an OGER installation step. I've never used OGER before. Is setting that up manually a prerequisite foe the RunNER installation?

```
Installed /usr/local/lib/python3.8/dist-packages/recommonmark-0.7.1-py3.8.egg
Searching for oger@ git+https://github.com/OntoGene/OGER@master
Reading https://pypi.org/simple/oger/
Couldn't find index page for 'oger' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
No local packages or working download links found for oger@ git+https://github.com/OntoGene/OGER@master
error: Could not find suitable distribution for Requirement.parse('oger@ git+https://github.com/OntoGene/OGER@master')
```

**Comment by turbomam** [comment]
I think I solved this with

`sudo pip install git+https://github.com/OntoGene/OGER.git`

**Comment by hrshdhgd** [comment]
Yes, runNER is a wrapper around OGER. So having OGER installed is crucial for everything to work as expected. Thanks for pointing out the OGER install issue. I am fixing this right now!
