### ISSUE TITLE
Can't install with pip install git+https... on new Mac

### ISSUE THREAD

**Issue by turbomam** [monarch-initiative/runner#8]
I'm setting up my new LBL Mac now. I just tried installing runner.

I used `pip install git+https://github.com/monarch-intiative/runner.git` to install runner on the Linux machine I was using previously. 

I have MFA enabled, but I think that's just for logging into the web interface? 

I am cloning all of my other GitHub repos now over ssh, like `git clone git@github.com:monarch-initiative/runner.git`. I have a passphrase enabled for that.

```bash
(venv) MAM@MAM-M74 biosample-analysis % pip install git+https://github.com/monarch-intiative/runner.git
Collecting git+https://github.com/monarch-intiative/runner.git
  Cloning https://github.com/monarch-intiative/runner.git to /private/var/folders/vt/f297tpjn6n1b6dwkcwhhnmxm0000gp/T/pip-req-build-6au71oqp
  Running command git clone -q https://github.com/monarch-intiative/runner.git /private/var/folders/vt/f297tpjn6n1b6dwkcwhhnmxm0000gp/T/pip-req-build-6au71oqp
Username for 'https://github.com': turbomam
Password for 'https://turbomam@github.com': 
  remote: Invalid username or password.
  fatal: Authentication failed for 'https://github.com/monarch-intiative/runner.git/'
ERROR: Command errored out with exit status 128: git clone -q https://github.com/monarch-intiative/runner.git /private/var/folders/vt/f297tpjn6n1b6dwkcwhhnmxm0000gp/T/pip-req-build-6au71oqp Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by hrshdhgd** [comment]
I think it was a security issue. I have granted your username adequate permissions. Try now.

**Comment by turbomam** [comment]
Thanks. That didn't help. I don't need to start a new shell or anything like that, do I?

**Comment by turbomam** [comment]
No, that didn't help.

I downloaded the zip archive and did `python -m pip install ~/Downloads/runner-master.zip`. I think that worked.

I would like to continue looking into why the `pip install git+https...` is failing on this new Mac. Let's keep one another informed of anything we figure out.

Alternatively, are you going to publish runner to PyPI sometime?

**Comment by hrshdhgd** [comment]
> I would like to continue looking into why the `pip install git+https...` is failing on this new Mac. Let's keep one another informed of anything we figure out.

Sounds good

> Alternatively, are you going to publish runner to PyPI sometime?

No plans as of now.

**Comment by hrshdhgd** [comment]
I just double checked - your `initiative` is misspelt and missing an 'I' after 'in...'.

**Comment by turbomam** [comment]
thanks, but I don't know what that means. Is `initiative` a file?

**Comment by turbomam** [comment]
sorry about that. with your suggested spelling correction, it "just works"
